// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismicT from "@prismicio/types";
import type * as prismic from "@prismicio/client";

type Simplify<T> = {
    [KeyType in keyof T]: T[KeyType];
};
/** Content for Homepage documents */
interface HomepageDocumentData {
    /**
     * Title field in *Homepage*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: homepage.title
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    title: prismicT.KeyTextField;
    /**
     * Slice Zone field in *Homepage*
     *
     * - **Field Type**: Slice Zone
     * - **Placeholder**: *None*
     * - **API ID Path**: homepage.slices[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/slices
     *
     */
    slices: prismicT.SliceZone<HomepageDocumentDataSlicesSlice>;
    /**
     * NO INDEX field in *Homepage*
     *
     * - **Field Type**: Boolean
     * - **Placeholder**: *None*
     * - **Default Value**: false
     * - **API ID Path**: homepage.no_index
     * - **Tab**: SEO TAB
     * - **Documentation**: https://prismic.io/docs/core-concepts/boolean
     *
     */
    no_index: prismicT.BooleanField;
    /**
     * Canonical URL field in *Homepage*
     *
     * - **Field Type**: Link
     * - **Placeholder**: *None*
     * - **API ID Path**: homepage.canonical_url
     * - **Tab**: SEO TAB
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    canonical_url: prismicT.LinkField;
    /**
     * Meta title field in *Homepage*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: homepage.meta_title
     * - **Tab**: SEO TAB
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    meta_title: prismicT.KeyTextField;
    /**
     * Meta description field in *Homepage*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: homepage.meta_description
     * - **Tab**: SEO TAB
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    meta_description: prismicT.KeyTextField;
    /**
     * OG title field in *Homepage*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: homepage.og_title
     * - **Tab**: SEO TAB
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    og_title: prismicT.KeyTextField;
    /**
     * OG description field in *Homepage*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: homepage.og_description
     * - **Tab**: SEO TAB
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    og_description: prismicT.KeyTextField;
    /**
     * OG image field in *Homepage*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: homepage.og_image
     * - **Tab**: SEO TAB
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    og_image: prismicT.ImageField<never>;
}
/**
 * Slice for *Homepage → Slice Zone*
 *
 */
type HomepageDocumentDataSlicesSlice = HeroSliceSlice | ImageFeaturedStandardSlice | BookTableSlice | LoveContentSlice | TestimonialsGallerySlice;
/**
 * Homepage document from Prismic
 *
 * - **API ID**: `homepage`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomepageDocument<Lang extends string = string> = prismicT.PrismicDocumentWithUID<Simplify<HomepageDocumentData>, "homepage", Lang>;
/** Content for Page documents */
interface StandardpageDocumentData {
    /**
     * Title field in *Page*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: standardpage.title
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    title: prismicT.KeyTextField;
    /**
     * Slice Zone field in *Page*
     *
     * - **Field Type**: Slice Zone
     * - **Placeholder**: *None*
     * - **API ID Path**: standardpage.slices[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/slices
     *
     */
    slices: prismicT.SliceZone<StandardpageDocumentDataSlicesSlice>;
    /**
     * NO INDEX field in *Page*
     *
     * - **Field Type**: Boolean
     * - **Placeholder**: *None*
     * - **Default Value**: false
     * - **API ID Path**: standardpage.no_index
     * - **Tab**: SEO tab
     * - **Documentation**: https://prismic.io/docs/core-concepts/boolean
     *
     */
    no_index: prismicT.BooleanField;
    /**
     * Canonical URL field in *Page*
     *
     * - **Field Type**: Link
     * - **Placeholder**: *None*
     * - **API ID Path**: standardpage.canonical_url
     * - **Tab**: SEO tab
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    canonical_url: prismicT.LinkField;
    /**
     * Meta title field in *Page*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: standardpage.meta_title
     * - **Tab**: SEO tab
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    meta_title: prismicT.KeyTextField;
    /**
     * Meta description field in *Page*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: standardpage.meta_description
     * - **Tab**: SEO tab
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    meta_description: prismicT.KeyTextField;
    /**
     * OG title field in *Page*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: standardpage.og_title
     * - **Tab**: SEO tab
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    og_title: prismicT.KeyTextField;
    /**
     * OG description field in *Page*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: standardpage.og_description
     * - **Tab**: SEO tab
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    og_description: prismicT.KeyTextField;
    /**
     * OG image field in *Page*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: standardpage.og_image
     * - **Tab**: SEO tab
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    og_image: prismicT.ImageField<never>;
    /**
     * Active redirect field in *Page*
     *
     * - **Field Type**: Boolean
     * - **Placeholder**: *None*
     * - **Default Value**: false
     * - **API ID Path**: standardpage.active_redirect
     * - **Tab**: Redirect
     * - **Documentation**: https://prismic.io/docs/core-concepts/boolean
     *
     */
    active_redirect: prismicT.BooleanField;
    /**
     * Redirect link field in *Page*
     *
     * - **Field Type**: Link
     * - **Placeholder**: *None*
     * - **API ID Path**: standardpage.redirect_link
     * - **Tab**: Redirect
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    redirect_link: prismicT.LinkField;
}
/**
 * Slice for *Page → Slice Zone*
 *
 */
type StandardpageDocumentDataSlicesSlice = HeroSliceSlice | ImageGallerySlice;
/**
 * Page document from Prismic
 *
 * - **API ID**: `standardpage`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type StandardpageDocument<Lang extends string = string> = prismicT.PrismicDocumentWithUID<Simplify<StandardpageDocumentData>, "standardpage", Lang>;
export type AllDocumentTypes = HomepageDocument | StandardpageDocument;
/**
 * Primary content in BookTable → Primary
 *
 */
interface BookTableSliceDefaultPrimary {
    /**
     * emoji field in *BookTable → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: book_table.primary.emoji
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    emoji: prismicT.KeyTextField;
    /**
     * Title field in *BookTable → Primary*
     *
     * - **Field Type**: Title
     * - **Placeholder**: This is where it all begins...
     * - **API ID Path**: book_table.primary.title
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    title: prismicT.TitleField;
    /**
     * BookTable field in *BookTable → Primary*
     *
     * - **Field Type**: Title
     * - **Placeholder**: *None*
     * - **API ID Path**: book_table.primary.booktable
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    booktable: prismicT.TitleField;
    /**
     * CTA internal field in *BookTable → Primary*
     *
     * - **Field Type**: Content Relationship
     * - **Placeholder**: *None*
     * - **API ID Path**: book_table.primary.cta_internal
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    cta_internal: prismicT.RelationField;
    /**
     * CTA Text field in *BookTable → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: book_table.primary.cta_text
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    cta_text: prismicT.KeyTextField;
}
/**
 * Item in BookTable → Items
 *
 */
export interface BookTableSliceDefaultItem {
    /**
     * paragraph field in *BookTable → Items*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: book_table.items[].paragraph
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    paragraph: prismicT.RichTextField;
}
/**
 * Default variation for BookTable Slice
 *
 * - **API ID**: `default`
 * - **Description**: `BookTable`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type BookTableSliceDefault = prismicT.SharedSliceVariation<"default", Simplify<BookTableSliceDefaultPrimary>, Simplify<BookTableSliceDefaultItem>>;
/**
 * Slice variation for *BookTable*
 *
 */
type BookTableSliceVariation = BookTableSliceDefault;
/**
 * BookTable Shared Slice
 *
 * - **API ID**: `book_table`
 * - **Description**: `BookTable`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type BookTableSlice = prismicT.SharedSlice<"book_table", BookTableSliceVariation>;
/**
 * Primary content in HeroSlice → Primary
 *
 */
interface HeroSliceSliceDefaultPrimary {
    /**
     * Title field in *HeroSlice → Primary*
     *
     * - **Field Type**: Title
     * - **Placeholder**: This is where it all begins...
     * - **API ID Path**: hero_slice.primary.title
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    title: prismicT.TitleField;
    /**
     * Description field in *HeroSlice → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: A nice description of your feature
     * - **API ID Path**: hero_slice.primary.description
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    description: prismicT.RichTextField;
    /**
     * image field in *HeroSlice → Primary*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: hero_slice.primary.image
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    image: prismicT.ImageField<never>;
}
/**
 * Item in HeroSlice → Items
 *
 */
export interface HeroSliceSliceDefaultItem {
    /**
     * CTA Link field in *HeroSlice → Items*
     *
     * - **Field Type**: Link
     * - **Placeholder**: *None*
     * - **API ID Path**: hero_slice.items[].cta_link
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    cta_link: prismicT.LinkField;
    /**
     * CTA Text field in *HeroSlice → Items*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: hero_slice.items[].cta_text
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    cta_text: prismicT.KeyTextField;
}
/**
 * Default variation for HeroSlice Slice
 *
 * - **API ID**: `default`
 * - **Description**: `HeroSlice`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type HeroSliceSliceDefault = prismicT.SharedSliceVariation<"default", Simplify<HeroSliceSliceDefaultPrimary>, Simplify<HeroSliceSliceDefaultItem>>;
/**
 * Slice variation for *HeroSlice*
 *
 */
type HeroSliceSliceVariation = HeroSliceSliceDefault;
/**
 * HeroSlice Shared Slice
 *
 * - **API ID**: `hero_slice`
 * - **Description**: `HeroSlice`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type HeroSliceSlice = prismicT.SharedSlice<"hero_slice", HeroSliceSliceVariation>;
/**
 * Primary content in ImageFeaturedStandard → Primary
 *
 */
interface ImageFeaturedStandardSliceDefaultPrimary {
    /**
     * subtitle field in *ImageFeaturedStandard → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: image_featured_standard.primary.subtitle
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    subtitle: prismicT.KeyTextField;
    /**
     * Secondary Heading field in *ImageFeaturedStandard → Primary*
     *
     * - **Field Type**: Title
     * - **Placeholder**: This is where it all begins...
     * - **API ID Path**: image_featured_standard.primary.secondary_heading
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    secondary_heading: prismicT.TitleField;
    /**
     * CTA Link field in *ImageFeaturedStandard → Primary*
     *
     * - **Field Type**: Link
     * - **Placeholder**: *None*
     * - **API ID Path**: image_featured_standard.primary.cta_link
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    cta_link: prismicT.LinkField;
    /**
     * CTA Text field in *ImageFeaturedStandard → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: image_featured_standard.primary.cta_text
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    cta_text: prismicT.KeyTextField;
    /**
     * Image field in *ImageFeaturedStandard → Primary*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: image_featured_standard.primary.image
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    image: prismicT.ImageField<never>;
    /**
     * CTA Internal field in *ImageFeaturedStandard → Primary*
     *
     * - **Field Type**: Content Relationship
     * - **Placeholder**: *None*
     * - **API ID Path**: image_featured_standard.primary.cta_internal
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    cta_internal: prismicT.RelationField;
    /**
     * CTA internal text field in *ImageFeaturedStandard → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: image_featured_standard.primary.cta_internal_text
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    cta_internal_text: prismicT.KeyTextField;
}
/**
 * Item in ImageFeaturedStandard → Items
 *
 */
export interface ImageFeaturedStandardSliceDefaultItem {
    /**
     * Paragraph field in *ImageFeaturedStandard → Items*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: image_featured_standard.items[].paragraph
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    paragraph: prismicT.RichTextField;
}
/**
 * Default variation for ImageFeaturedStandard Slice
 *
 * - **API ID**: `default`
 * - **Description**: `ImageFeaturedStandard`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type ImageFeaturedStandardSliceDefault = prismicT.SharedSliceVariation<"default", Simplify<ImageFeaturedStandardSliceDefaultPrimary>, Simplify<ImageFeaturedStandardSliceDefaultItem>>;
/**
 * Slice variation for *ImageFeaturedStandard*
 *
 */
type ImageFeaturedStandardSliceVariation = ImageFeaturedStandardSliceDefault;
/**
 * ImageFeaturedStandard Shared Slice
 *
 * - **API ID**: `image_featured_standard`
 * - **Description**: `ImageFeaturedStandard`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type ImageFeaturedStandardSlice = prismicT.SharedSlice<"image_featured_standard", ImageFeaturedStandardSliceVariation>;
/**
 * Primary content in ImageGallery → Primary
 *
 */
interface ImageGallerySliceDefaultPrimary {
    /**
     * Title field in *ImageGallery → Primary*
     *
     * - **Field Type**: Title
     * - **Placeholder**: This is where it all begins...
     * - **API ID Path**: image_gallery.primary.title
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    title: prismicT.TitleField;
    /**
     * Description field in *ImageGallery → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: A nice description of your feature
     * - **API ID Path**: image_gallery.primary.description
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    description: prismicT.RichTextField;
}
/**
 * Item in ImageGallery → Items
 *
 */
export interface ImageGallerySliceDefaultItem {
    /**
     * Image field in *ImageGallery → Items*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: image_gallery.items[].image
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    image: prismicT.ImageField<never>;
}
/**
 * Default variation for ImageGallery Slice
 *
 * - **API ID**: `default`
 * - **Description**: `ImageGallery`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type ImageGallerySliceDefault = prismicT.SharedSliceVariation<"default", Simplify<ImageGallerySliceDefaultPrimary>, Simplify<ImageGallerySliceDefaultItem>>;
/**
 * Slice variation for *ImageGallery*
 *
 */
type ImageGallerySliceVariation = ImageGallerySliceDefault;
/**
 * ImageGallery Shared Slice
 *
 * - **API ID**: `image_gallery`
 * - **Description**: `ImageGallery`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type ImageGallerySlice = prismicT.SharedSlice<"image_gallery", ImageGallerySliceVariation>;
/**
 * Primary content in LoveContent → Primary
 *
 */
interface LoveContentSliceDefaultPrimary {
    /**
     * TitleImpact field in *LoveContent → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: love_content.primary.titleimpact
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    titleimpact: prismicT.RichTextField;
    /**
     * Sentence field in *LoveContent → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: love_content.primary.sentence
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    sentence: prismicT.KeyTextField;
}
/**
 * Default variation for LoveContent Slice
 *
 * - **API ID**: `default`
 * - **Description**: `LoveContent`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type LoveContentSliceDefault = prismicT.SharedSliceVariation<"default", Simplify<LoveContentSliceDefaultPrimary>, never>;
/**
 * Slice variation for *LoveContent*
 *
 */
type LoveContentSliceVariation = LoveContentSliceDefault;
/**
 * LoveContent Shared Slice
 *
 * - **API ID**: `love_content`
 * - **Description**: `LoveContent`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type LoveContentSlice = prismicT.SharedSlice<"love_content", LoveContentSliceVariation>;
/**
 * Primary content in TestimonialsGallery → Primary
 *
 */
interface TestimonialsGallerySliceDefaultPrimary {
    /**
     * subtitle field in *TestimonialsGallery → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: testimonials_gallery.primary.subtitle
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    subtitle: prismicT.KeyTextField;
    /**
     * Title field in *TestimonialsGallery → Primary*
     *
     * - **Field Type**: Title
     * - **Placeholder**: This is where it all begins...
     * - **API ID Path**: testimonials_gallery.primary.title
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    title: prismicT.TitleField;
    /**
     * Image1 field in *TestimonialsGallery → Primary*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: testimonials_gallery.primary.image1
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    image1: prismicT.ImageField<never>;
    /**
     * Image2 field in *TestimonialsGallery → Primary*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: testimonials_gallery.primary.image2
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    image2: prismicT.ImageField<never>;
    /**
     * Image3 field in *TestimonialsGallery → Primary*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: testimonials_gallery.primary.image3
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    image3: prismicT.ImageField<never>;
    /**
     * Image4 field in *TestimonialsGallery → Primary*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: testimonials_gallery.primary.image4
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    image4: prismicT.ImageField<never>;
    /**
     * Image5 field in *TestimonialsGallery → Primary*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: testimonials_gallery.primary.image5
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    image5: prismicT.ImageField<never>;
    /**
     * Image6 field in *TestimonialsGallery → Primary*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: testimonials_gallery.primary.image6
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    image6: prismicT.ImageField<never>;
}
/**
 * Default variation for TestimonialsGallery Slice
 *
 * - **API ID**: `default`
 * - **Description**: `TestimonialsGallery`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type TestimonialsGallerySliceDefault = prismicT.SharedSliceVariation<"default", Simplify<TestimonialsGallerySliceDefaultPrimary>, never>;
/**
 * Slice variation for *TestimonialsGallery*
 *
 */
type TestimonialsGallerySliceVariation = TestimonialsGallerySliceDefault;
/**
 * TestimonialsGallery Shared Slice
 *
 * - **API ID**: `testimonials_gallery`
 * - **Description**: `TestimonialsGallery`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type TestimonialsGallerySlice = prismicT.SharedSlice<"testimonials_gallery", TestimonialsGallerySliceVariation>;
declare module "@prismicio/client" {
    interface CreateClient {
        (repositoryNameOrEndpoint: string, options?: prismic.ClientConfig): prismic.Client<AllDocumentTypes>;
    }
    namespace Content {
        export type { HomepageDocumentData, HomepageDocumentDataSlicesSlice, HomepageDocument, StandardpageDocumentData, StandardpageDocumentDataSlicesSlice, StandardpageDocument, AllDocumentTypes, BookTableSliceDefaultPrimary, BookTableSliceDefaultItem, BookTableSliceDefault, BookTableSliceVariation, BookTableSlice, HeroSliceSliceDefaultPrimary, HeroSliceSliceDefaultItem, HeroSliceSliceDefault, HeroSliceSliceVariation, HeroSliceSlice, ImageFeaturedStandardSliceDefaultPrimary, ImageFeaturedStandardSliceDefaultItem, ImageFeaturedStandardSliceDefault, ImageFeaturedStandardSliceVariation, ImageFeaturedStandardSlice, ImageGallerySliceDefaultPrimary, ImageGallerySliceDefaultItem, ImageGallerySliceDefault, ImageGallerySliceVariation, ImageGallerySlice, LoveContentSliceDefaultPrimary, LoveContentSliceDefault, LoveContentSliceVariation, LoveContentSlice, TestimonialsGallerySliceDefaultPrimary, TestimonialsGallerySliceDefault, TestimonialsGallerySliceVariation, TestimonialsGallerySlice };
    }
}
