// Code generated by Slice Machine. DO NOT EDIT.

import HeroSlice from './HeroSlice';
import ImageGallery from './ImageGallery';

export {
	HeroSlice,
	ImageGallery,
};

export const components = {
	hero_slice: HeroSlice,
	image_gallery: ImageGallery,
};
