// Code generated by Slice Machine. DO NOT EDIT.

import AddressesBox from './AddressesBox';
import AllergyBox from './AllergyBox';
import BannerSlice from './BannerSlice';
import BookTable from './BookTable';
import DrinksMenu from './DrinksMenu';
import GalleryList from './GalleryList';
import HeroSlice from './HeroSlice';
import ImageFeaturedStandard from './ImageFeaturedStandard';
import ImageGallery from './ImageGallery';
import LoveContent from './LoveContent';
import MainMenu from './MainMenu';
import MapBox from './MapBox';
import StoryFeatured from './StoryFeatured';
import TeamSlice from './TeamSlice';
import TestimonialsGallery from './TestimonialsGallery';
import ValuesList from './ValuesList';
import VeganMenu from './VeganMenu';

export {
	AddressesBox,
	AllergyBox,
	BannerSlice,
	BookTable,
	DrinksMenu,
	GalleryList,
	HeroSlice,
	ImageFeaturedStandard,
	ImageGallery,
	LoveContent,
	MainMenu,
	MapBox,
	StoryFeatured,
	TeamSlice,
	TestimonialsGallery,
	ValuesList,
	VeganMenu,
};

export const components = {
	addresses_box: AddressesBox,
	allergy_box: AllergyBox,
	banner: BannerSlice,
	book_table: BookTable,
	drinks_menu: DrinksMenu,
	gallery_list: GalleryList,
	hero_slice: HeroSlice,
	image_featured_standard: ImageFeaturedStandard,
	image_gallery: ImageGallery,
	love_content: LoveContent,
	main_menu: MainMenu,
	map_box: MapBox,
	story_featured: StoryFeatured,
	team_slice: TeamSlice,
	testimonials_gallery: TestimonialsGallery,
	values_list: ValuesList,
	vegan_menu: VeganMenu,
};
