// Code generated by Slice Machine. DO NOT EDIT.

import BookTable from './BookTable';
import HeroSlice from './HeroSlice';
import ImageFeaturedStandard from './ImageFeaturedStandard';
import ImageGallery from './ImageGallery';
import LoveContent from './LoveContent';

export {
	BookTable,
	HeroSlice,
	ImageFeaturedStandard,
	ImageGallery,
	LoveContent,
};

export const components = {
	book_table: BookTable,
	hero_slice: HeroSlice,
	image_featured_standard: ImageFeaturedStandard,
	image_gallery: ImageGallery,
	love_content: LoveContent,
};
